### ISSUE TITLE
Monkey2 Roadmap

### ISSUE THREAD

**Issue by Pharmhaus-2** [blitz-foundation/monkey2#2]
- [x] Migrate existing tickets from blitz-research/monkey2 and classify them
- [x] Shallow copy of roadmap from http://monkeycoder.co.nz/monkey2-roadmap/
- [ ] Website and forum for Monkey2.org
- [ ] Create a release page for monkey2 releases

**Comment by Pharmhaus-2** [comment]
### The Monkey 2 TODO List!

This is a list of features currently under develop or in consideration for monkey2. Please note this list is subject to change.
### Mojo

-     Bitmap font support (any requests for file formats?)

### Mojo3d

-     Scene serialization, mojo3d only to start with, try to generalize for anything a bit later.
-     Cleaned up  pbr shader system.
-     Terrain materials.
-     More precise transparent material sorting.
-     View culling.
-     Bake scene.

### MojoX

    Merge some of nerobot’s enhancements from ted2go, eg: menus, tooltips etc.
    ‘Property view’ system for reflection based editing of objects.
    ‘Property changed’ style system for use with property views.

### Std module

-     Simple event queue system for console apps so they can use fibers too.

### General

-     Log files and better error handling.
-     Profile config that just does function level debug info.

### Mx2cc

-     Big compiler cleanup, starting with at least translator.
-     Fix unreliable global initialization order.
-     Varargs system, probably Variant[] based.
-     Return type based overloading.
-     Threads (long term!).
